### PR TITLE
Lab00

### PR DESCRIPTION
**Pull request by SoilChang**
I updated lab00

### CODE REVIEW

**Comment by sijie123** [comment]
I think you might have committed / checked-out the wrong mkdocs.yml.
The one in your commit will make viewable every lecture 01-11,  and lab 1-10 etc that we used for last sem.

**Comment by SoilChang** [comment]
This is confusing lol. There is only one mkdocs.yml in the master branch. Where do I get the correct one?

**Comment by sijie123** [comment]
I think the issue happened during "resolve merge conflict" (commit [1e855d2](https://github.com/SoilChang/1718-s2/commit/1e855d25b61dfbc7163703e001e03fd49235a0da#diff-45ee620855dad847bea76b49932ad7db). Right before that, @weitsang pushed a commit that removed all the links (as reflected in master right now). The merge conflict resolution probably added all that back.

**Comment by SoilChang** [comment]
I pull from upstream master and @weitsang  added polymorphism to lect 2 title. That's all. Can be seen in the file comparison. The rest of the lectures seems to be added because I changed all the files from lecx to lec0x otherwise mkdocs will complain cannot find files

**Comment by sijie123** [comment]
image

You might want to take a look at the current master's mkdocs.yml?
I was trying to mean something like the one in the screenshot - only have lec01 and lec02, and not lec03-10.

I think you can commit a new patch that removes the "extra" lec pages from mkdocs.yml.

**Comment by SoilChang** [comment]
I see. I don't know how prof decide to manage the branches because there is only 1 branch. I think there should be a development branch because if I deleted the rest, the rest won't show up in localhost which make testing very hard.

**Pull request merged**
